name: Pull Requests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3

      - name: Install dependencies
        run: yarn
      - name: Test
        run: yarn affected:test
      - name: Lint
        run: yarn affected:lint
      - name: Build
        run: yarn affected:build
